add ability to write secrets for amplify app
cloudposse/terraform-aws-amplify-app pull request #33
Opened 2024-04-30 18:44 UTC by kevcube

## what

Amplify can access secrets during build and runtime
This PR allows the 

## why

It may be useful depending on a user's secrets management pattern to write secrets here when creating the amplify app.

## references

https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#environment-secrets

2024-06-20 22:16 UTC, goruha commented
/terratest

2024-07-22 16:43 UTC, kevcube commented
/terratest

2024-07-22 18:07 UTC, goruha commented
@kevcube, why can't a secret be written externally based on the module's outputs after the Amplify app is created?

2024-07-22 18:07 UTC, goruha reviewed
@kevcube, why can't a secret be written externally based on the module's outputs after the Amplify app is created?

2024-07-22 18:27 UTC, kevcube commented
> @kevcube, why can't a secret be written externally based on the module's outputs after the Amplify app is created?

It can be written externally, if someone wants to use remote-state or something to grab the amplify ID that's an option, but because amplify has the ability to access secrets stored at these predefined paths I thought it made sense to package in this  module because they can be considered a part of the amplify application stack

2024-07-25 22:09 UTC, goruha commented
/terratest

2024-07-25 22:09 UTC, goruha approved these changes

2024-07-25 22:14 UTC, goruha requested changes
@kevcube tests failed 
https://github.com/cloudposse/actions/actions/runs/10102221318/job/27937411342

2024-07-25 22:25 UTC, goruha requested changes

2024-07-25 22:25 UTC, goruha commented on main.tf
> +}
```suggestion
resource "aws_ssm_parameter" "default" {
  for_each    = local.environments
  name          = format("/amplify/%s/%s/%s", one(aws_amplify_app.default[*].id), each.key, secret_key)
  description = "AWS Amplify secret."
  type          = "SecureString"
  tier               = "Standard"
  value            = secret_value
  overwrite     = "false"
  data_type    = "text"
  
  tags = module.this.tags
}
```

2024-10-13 15:42 UTC, closed without merging